---
name: Acme-Colour-Fuzzy
version: 0.01
author:
  - 'Mattia Barbon <mbarbon@cpan.org>'
abstract: give names to arbitrary RGB triplets
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0.30
  Color::Similarity::HCL: 0.01
  Graphics::ColorNames: 1.00
  Graphics::ColorNames::VACCC: 1.00
  List::Util: 0.01
  Module::Build: 0.2607
  Test::More: 0.48
  perl: 5.6.0
provides:
  Acme::Colour::Fuzzy:
    file: lib/Acme/Colour/Fuzzy.pm
    version: 0.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
